---
variant: fcos
version: 1.0.0
storage:
  files:
    - path: /etc/kubernetes/kubeadm-custom-config.yaml
      mode: 0644
      contents:
        inline: |
          ---
          apiVersion: kubeadm.k8s.io/v1beta2
          kind: InitConfiguration
          bootstrapTokens:
            - groups:
                - system:bootstrappers:kubeadm:default-node-token
              token: m41n6u.ix7tfu70yj9h94iw
              ttl: 24h0m0s
              usages:
                - signing
                - authentication
          localAPIEndpoint:
            advertiseAddress: ${advertise_ip}
            bindPort: 6443
          nodeRegistration:
            criSocket: /run/containerd/containerd.sock
            name: ${domain_name}
            taints:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
          ---
          apiVersion: kubeadm.k8s.io/v1beta2
          kind: ClusterConfiguration
          kubernetesVersion: ${kubernetes_version}
          apiServer:
            extraArgs:
              advertise-address: ${advertise_ip}
            timeoutForControlPlane: 4m0s
          certificatesDir: /etc/kubernetes/pki
          clusterName: kubernetes
          controllerManager:
            extraArgs:
              flex-volume-plugin-dir: /var/lib/kubelet/kubelet-plugins/volume/exec
          dns:
            type: CoreDNS
          etcd:
            local:
              dataDir: /var/lib/etcd
          imageRepository: k8s.gcr.io
          networking:
            dnsDomain: cluster.local
            podSubnet: ${pod_subnet}
            serviceSubnet: ${service_subnet}
          scheduler: {}
          ...