---
variant: fcos
version: 1.0.0
storage:
  files:
    - path: /etc/kubernetes/kubeadm-custom-config.yaml
      mode: 0644
      contents:
        inline: |
          ---
          # https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2
          apiVersion: kubeadm.k8s.io/v1beta2
          kind: InitConfiguration
          localAPIEndpoint:
            %{~ if advertise_ip != null ~}
            advertiseAddress: ${advertise_ip}
            %{~ endif ~}
            bindPort: 6443
          nodeRegistration:
            criSocket: /run/containerd/containerd.sock
            name: ${domain_name}
          ---
          apiVersion: kubeadm.k8s.io/v1beta2
          kind: ClusterConfiguration
          kubernetesVersion: ${kubernetes_version}
          apiServer:
            %{~ if advertise_ip != null ~}
            extraArgs:
              advertise-address: ${advertise_ip}
            %{~ endif ~}
            timeoutForControlPlane: 4m0s
            %{~ if apiserver_extra_sans != null ~}
            certSANs:
              %{~ for san in apiserver_extra_sans ~}
              - ${san}
              %{~ endfor ~}
            %{~ endif ~}
          clusterName: kubernetes
          controllerManager:
            extraArgs:
              flex-volume-plugin-dir: /var/lib/kubelet/kubelet-plugins/volume/exec
          networking:
            dnsDomain: cluster.local
            podSubnet: ${pod_subnet}
            serviceSubnet: ${service_subnet}
          ---
          apiVersion: kubeproxy.config.k8s.io/v1alpha1
          kind: KubeProxyConfiguration
          mode: "ipvs"
          ipvs:
            strictARP: true
          ...
