---
variant: fcos
version: 1.0.0
storage:
  files:
    - path: /etc/modules-load.d/80-k8s.conf
      mode: 0644
      contents:
        inline: |
          br_netfilter
    - path: /etc/sysctl.d/80-k8s.conf
      mode: 0644
      contents:
        inline: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          vm.swappiness = 0
    %{~ for nic, conf in net_config ~}
    - path: /etc/NetworkManager/system-connections/${nic}.nmconnection
      mode: 0600
      overwrite: true
      contents:
        inline: |
          [connection]
          %{~ for key, value in merge({
                                        "id"="${nic}",
                                        "interface-name"="${nic}",
                                        "type"="ethernet"
                                      }, lookup(conf, "connection", {})) ~}
          ${key}=${value}
          %{~ endfor ~}
          %{~ for cfgKey in setsubtract(keys(conf), ["connection"]) ~}
          [${cfgKey}]
          %{~ for key, value in conf[cfgKey] ~}
          ${key}=${value}
          %{~ endfor ~}
          %{~ endfor ~}
    %{~ endfor ~}

