---
variant: fcos
version: 1.0.0
storage:
  files:
%{ for cfg in net-config ~}
    - path: /etc/NetworkManager/system-connections/${cfg.interface}.nmconnection
      mode: 0600
      overwrite: true
      contents:
        inline: |
          [connection]
          interface-name=${cfg.interface}
          type=ethernet
          [ethernet]
          mac-address-blacklist=
          [ipv4]
          %{~ if cfg.auto != null ~}
          method=auto
          never-default=${cfg.auto.never_default}
          ignore-auto-dns=${cfg.auto.ignore_auto_dns}
          %{~ else ~}
          %{~ if cfg.manual != null ~}
          method=manual
          addresses=${cfg.manual.ipnet}${ cfg.manual.gateway != null ? format(",%s",cfg.manual.gateway) : ""}
          dns=${cfg.manual.dns == null ? "" : cfg.manual.dns}
          %{~ endif ~}
          %{~ endif ~}
          [ipv6]
          addr-gen-mode=stable-privacy
          dns-search=
          method=auto
          [proxy]
%{ endfor ~}
